"""Thin async client for the WaSender API.

Two credential tiers:
  - Personal Access Token (PAT): one global key, used for session management.
  - Session API key: one per org, generated by WaSender on connect, used to send.
"""
import asyncio
import logging

import httpx

from app.config import get_settings

logger = logging.getLogger(__name__)
_TIMEOUT = httpx.Timeout(20.0)
# Force IPv4 — uvloop (used by uvicorn) does not fall back from IPv6 to IPv4
# when IPv6 sockets are present but unroutable.
_TRANSPORT = httpx.AsyncHTTPTransport(local_address="0.0.0.0")


def _base() -> str:
    return get_settings().wasender_base_url.rstrip("/")


def _pat_headers() -> dict:
    s = get_settings()
    if not s.wasender_pat:
        raise RuntimeError("WASENDER_PAT is not configured.")
    return {"Authorization": f"Bearer {s.wasender_pat}", "Content-Type": "application/json"}


async def _request(method: str, path: str, *, headers: dict, json: dict | None = None) -> dict:
    async with httpx.AsyncClient(timeout=_TIMEOUT, transport=_TRANSPORT) as client:
        r = await client.request(method, f"{_base()}{path}", headers=headers, json=json)
    if r.status_code >= 400:
        level = logger.error if r.status_code >= 500 else logger.warning
        level("WaSender %s %s → %s %s", method, path, r.status_code, r.text[:300])
        r.raise_for_status()
    return r.json() if r.content else {}


# --- Session management (PAT) ---

def _e164(phone: str) -> str:
    """Normalise to E.164: strip all non-digit chars, then re-add leading +."""
    digits = "".join(c for c in phone if c.isdigit())
    return f"+{digits}"


async def list_sessions() -> list[dict]:
    payload = await _request("GET", "/whatsapp-sessions", headers=_pat_headers())
    return payload.get("data", payload) if isinstance(payload.get("data"), list) else []


async def create_session(name: str, phone_number: str) -> dict:
    """Create a new WaSender session. If the number is already registered,
    returns the existing session instead of raising."""
    body = {
        "name": name,
        "phone_number": _e164(phone_number),
        "account_protection": False,
    }
    try:
        payload = await _request("POST", "/whatsapp-sessions", headers=_pat_headers(), json=body)
        return payload.get("data", payload)
    except httpx.HTTPStatusError as exc:
        # WaSender returns 422 "already taken" when the number is registered to
        # this account — look up and return that session instead of failing.
        if exc.response.status_code == 422 and "already been taken" in exc.response.text:
            sessions = await list_sessions()
            normed_digits = "".join(c for c in phone_number if c.isdigit())
            match = next(
                (
                    s for s in sessions
                    if "".join(c for c in (s.get("phone_number") or "") if c.isdigit()) == normed_digits
                ),
                None,
            )
            if match:
                logger.info("Session for %s already exists (id=%s) — reusing", normed_digits, match["id"])
                return match
        raise


async def delete_session(session_id: int) -> None:
    await _request("DELETE", f"/whatsapp-sessions/{session_id}", headers=_pat_headers())


async def update_session(session_id: int, **fields) -> dict:
    payload = await _request("PUT", f"/whatsapp-sessions/{session_id}", headers=_pat_headers(), json=fields)
    return payload.get("data", payload)


async def connect_session(session_id: int) -> dict:
    return await _request("POST", f"/whatsapp-sessions/{session_id}/connect", headers=_pat_headers())


async def disconnect_session(session_id: int) -> dict:
    return await _request("POST", f"/whatsapp-sessions/{session_id}/disconnect", headers=_pat_headers())


async def get_session(session_id: int) -> dict:
    payload = await _request("GET", f"/whatsapp-sessions/{session_id}", headers=_pat_headers())
    return payload.get("data", payload)


async def get_qr(session_id: int) -> str:
    payload = await _request("GET", f"/whatsapp-sessions/{session_id}/qrcode", headers=_pat_headers())
    return payload.get("data", payload).get("qrCode", "")


# --- Messaging (session API key) ---

def _session_headers(api_key: str) -> dict:
    return {"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}


async def send_text(api_key: str, to: str, text: str) -> dict:
    return await _request("POST", "/send-message", headers=_session_headers(api_key), json={"to": to, "text": text})


async def decrypt_media(api_key: str, message: dict) -> str | None:
    """Decrypt an inbound WhatsApp media message. Returns a 1-hour public URL or None."""
    try:
        payload = await _request(
            "POST", "/decrypt-media",
            headers=_session_headers(api_key),
            json={"data": {"messages": message}},
        )
        url = payload.get("publicUrl")
        if not url:
            logger.warning("decrypt_media: no publicUrl in response | %s", str(payload)[:300])
        return url
    except Exception:
        logger.warning("Media decrypt failed", exc_info=True)
        return None


async def send_image(api_key: str, to: str, image_url: str, caption: str = "") -> dict:
    body: dict = {"to": to, "imageUrl": image_url}
    if caption:
        body["text"] = caption
    return await _request("POST", "/send-image-message", headers=_session_headers(api_key), json=body)


async def send_video(api_key: str, to: str, video_url: str, caption: str = "") -> dict:
    body: dict = {"to": to, "videoUrl": video_url}
    if caption:
        body["text"] = caption
    return await _request("POST", "/send-video-message", headers=_session_headers(api_key), json=body)


# --- Startup reconnect (best-effort self-heal) ---

async def reconnect_existing_sessions() -> None:
    """On boot, nudge every org's WhatsApp session back to connected.

    WaSender hosts the socket, so a redeploy rarely drops it — this just heals
    sessions that went 'disconnected' while we were down. 'need_scan' means the
    device was logged out and genuinely needs a fresh QR (logged, not auto-fixed).
    """
    if not get_settings().wasender_pat:
        return
    from app.utils.supabase_client import get_svc  # local import avoids any cycle

    svc = get_svc()
    res = await asyncio.to_thread(
        lambda: svc.table("organizations").select("id, wasender_session_id").execute()
    )
    orgs = [o for o in (res.data or []) if o.get("wasender_session_id")]

    async def _heal(org: dict) -> None:
        sid = org["wasender_session_id"]
        try:
            status = (await get_session(sid)).get("status")
            if status == "connected":
                return
            if status == "need_scan":
                logger.warning("Org %s session %s needs a QR re-scan (logged out)", org["id"], sid)
                return
            await connect_session(sid)
            logger.info("Reconnected org %s session %s (was %s)", org["id"], sid, status)
        except httpx.HTTPStatusError as exc:
            code = exc.response.status_code
            if code == 404:
                logger.warning("Org %s session %s no longer exists on WaSender (404) — skipping", org["id"], sid)
            elif code == 403:
                logger.warning("Org %s session %s is on a different WaSender account (403) — skipping", org["id"], sid)
            else:
                logger.exception("Reconnect failed for org %s session %s", org["id"], sid)
        except httpx.RequestError as exc:
            # Covers ConnectError, ReadError, WriteError, TimeoutException, etc.
            logger.warning("Org %s session %s — WaSender unreachable at startup (%s), skipping", org["id"], sid, type(exc).__name__)
        except Exception:
            logger.exception("Reconnect failed for org %s session %s", org["id"], sid)

    await asyncio.gather(*(_heal(o) for o in orgs))
